spring:
  application:
    name: property-report-service
  cloud:
    openfeign:
      client:
        config:
          land-registry: # Name of the Feign Client to configure
            connectTimeout: 2000 # Connection attempt timeout (ms)
            readTimeout : 1000    # read timeout (ms)

      circuitbreaker:
        enabled: true # # Enable circuit breaker feature for Feign

server:
  port: 8080

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
    instances:
      # Land Registry API policy considers 'slow calls' as failures
      land-registry:
        base-config: default
        slow-call-rate-threshold: 50 # Circuit OPEN if slow call rate exceeds 50%
        slow-call-duration-threshold: 700ms # Calls over 700ms are considered slow
      # Startup API policy considers 'exceptions' as failures
      market-price:
        base-config: default
        failure-rate-threshold: 50 # Circuit OPEN if exception rate exceeds 50%
